class Activity {
  final String userId;
  final String name;
  final String description;
  // TODO Implement activity card backgrounds using this style property
  final String style;
  final int order;
  String? _id;

  String? get id => _id;

  Activity(
      {required this.userId,
      required this.name,
      this.description = ' ',
      this.style = ' ',
      required this.order});

  Map<String, Object?> toDocument() => {
        'userId': userId,
        'name': name,
        'description': description,
        'style': style,
        'order': order,
      };

  factory Activity.fromDocument(Map<String, dynamic> json) {
    final activity = Activity(
      userId: json['userId'],
      name: json['name'],
      description: json['description'],
      // Style is unimplemented for now
      style: json['style'],
      order: json['order'],
    );

    // id is generated by RethinkDB
    activity._id = json['id'];
    return activity;
  }
}
