class User {
  final String email;
  String? _id;

  String? get id => _id;

  User({required this.email});

  Map<String, Object?> toDocument() => {'email': email};

  factory User.fromDocument(Map<String, dynamic> doc) {
    final user = User(email: doc['email']);
    // id is generated by RethinkDB
    user._id = doc['id'];
    return user;
  }
}
